title: Hugo Laviec

logo: /images/me.jpg
description: Welcome to my portfolio, where you'll find my resume, my research interests and some of my results.

show_downloads: True

theme: jekyll-theme-minimal

github:
  username: ltoguh

social: Hugo Laviec
  links: https://www.researchgate.net/profile/Hugo-Laviec?ev=hdr_xprf&_sg=ShFOu-DV4uDz_kbj8SD9VR003cxQUQQMgG5xyGrAvRjzr09jnyM7nNIzUNwBQdPIHuJYOMYsymXZC0omRYY1zXA4&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6ImhvbWUiLCJwYWdlIjoiaG9tZSIsInBvc2l0aW9uIjoiZ2xvYmFsSGVhZGVyIn19
